name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  
env:
    PROJECT_PATH: 'src/Aqua.StringHelpers.csproj'
    PACKAGE_OUTPUT_DIRECTORY: ${{ github.workspace }}\output
    NUGET_SOURCE_URL: 'https://api.nuget.org/v3/index.json'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: 'Pack project'
      run: dotnet restore ${{ env.PROJECT_PATH }} --output ${{ env.PACKAGE_OUTPUT_DIRECTORY }}
    - name: 'Push Package'
      run: dotnet nuget push ${{ env.PROJECT_PATH }}\*.nupkg -k ${{ secrets.NUGET_AUTH_TOKEN }} -s ${{ env.NUGET_SOURCE_URL }}

    
